remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme

title: TEAM-BE Tutorials
description: This page contains tutorials to use COLLECE-2.0 (COLLaborative Edition, Compilation and Execution of programs) along with the TEAM-BE automatic group formation tool. 
logo: /assets/img/logo.png