remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme

title: TEAM-BE Tutorials
description: Tutorials to use Collece 2.0 along with the TEAM-BE automatic group formation tool/
